[
  tools: [
    # ex_check 0.17 auto-detects usage_rules and runs `mix usage_rules.sync --check`,
    # which needs a `usage_rules:` config in mix.exs. AGENTS.md is still generated by
    # the `usage_rules.update` alias; re-enable once that moves to the config.
    {:usage_rules, false}
  ]
]
