[
  tools: [
    # ex_check 0.17 auto-detects usage_rules and runs `mix usage_rules.sync --check`,
    # which needs a `usage_rules:` config in mix.exs. AGENTS.md is still generated by
    # the `usage_rules.update` alias; re-enable once that moves to the config.
    {:usage_rules, false},
    # Sobelow's Vuln checks only match six 2017-18 CVEs (hex_audit covers
    # dependency advisories properly), and they parse mix.lock in a way
    # Elixir 1.20 warns about once per locked dependency.
    {:sobelow, "mix sobelow --exit --ignore Vuln"},
    # Match CI (ash-ci): the test env also compiles and checks test/support.
    {:doctor, "mix doctor --full --raise", env: %{"MIX_ENV" => "test"}}
  ]
]
